Visualization unit tests
dhmit/gender_analysis pull request #142
Opened 2020-10-30 17:02 UTC by wilke0818

These tests cover creating metadata-visualizations and usually check that the the files are successfully created with the correct filename and put into the correct directory. The changes in this PR also incorporate changes from #125 but has been structured to more generally create the output directories now and has moved the functionality for this into a common file.

2020-11-02 15:22 UTC, wilke0818 commented
@ryaanahmed fixed the issues with the unit tests that blocked it from passing on Github

2020-11-10 16:58 UTC, ryaanahmed commented on gender_analysis/common.py
> +def create_path_object_and_directories(output_dir, filename=None):
nice utility function!

2020-11-10 16:58 UTC, ryaanahmed requested changes
Looking really good. Requesting a few changes for readability.

Plz see my latest commit for how to use the `/` infix operator to construct paths. We don't need a hybrid of pathlib + os most of the time: pathlib has aliases for almost all of the os.path stuff, so better to just pick one and stick with it. (see https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module)

See particularly my changes to `test_create_path_object_and_directories` in the latest commit for an example of how to clean these up a little bit. If you could go through the rest of the `metadata_visualization_test` tests and similarly clean up, this will be in great shape.

2020-11-13 20:40 UTC, wilke0818 commented
@ryaanahmed Made the requested changes!

2020-11-17 17:02 UTC, ryaanahmed approved these changes

2020-11-17 17:03 UTC, ryaanahmed commented
Changes look good @wilke0818 - much clearer / less duplication.

Linter failures here are all in files heavily edited in #143 so leaving alone per discussion in #145 to avoid giant merge conflicts.

merging!

2020-11-17 17:03 UTC, merged