Novel module
dhmit/gender_analysis pull request #15
Opened 2019-06-19 19:23 UTC by meesuekim

- changed name of Novel class and file to  Document
- changed references of Novel and .novel to Document and .document
- fixed \r issues

2019-06-19 21:29 UTC, ryaanahmed requested changes
@meesuekim  --  this is still failing a lot of tests. Looks like in some places, you've changed the import statement for the 'novel' module correctly, but you're still calling "Novel" rather than "Document". I'll point out some places in comments.

2019-06-19 21:29 UTC, ryaanahmed commented on gender_analysis/analysis/analysis.py
> +    >>> scarlett = document.Novel(novel_metadata)
this needs to be, e.g., document.Document -- and though the above variable can stay named novel_metadata, it's probably better if we call it document_metadata

2019-06-19 21:30 UTC, ryaanahmed requested changes

2019-06-19 21:30 UTC, ryaanahmed commented on gender_analysis/analysis/analysis.py
> +    >>> scarlet = document.Novel(novel_metadata)
same deal here -- needs to be document.Document

2019-06-19 21:30 UTC, ryaanahmed commented on gender_analysis/analysis/analysis.py
> +    >>> scarlett = document.Novel(novel_metadata)
and so forth... (more below I think, but you get the picture)

2019-06-20 15:09 UTC, meesuekim commented
did some more refactoring.
should pass all tests now

2019-06-20 15:32 UTC, ryaanahmed approved these changes
Awesome! Looks good, passes tests. Merging.

2019-06-20 15:32 UTC, merged